const $=id=>document.getElementById(id);
const configured=window.SUPABASE_URL&&!window.SUPABASE_URL.includes("PEGA_AQUI")&&window.SUPABASE_ANON_KEY&&!window.SUPABASE_ANON_KEY.includes("PEGA_AQUI");
const sb=configured?window.supabase.createClient(window.SUPABASE_URL,window.SUPABASE_ANON_KEY):null;
let items=[],user=null,editing=null,file=null;
const catalog=$("catalog"),empty=$("empty"),search=$("search"),filter=$("categoryFilter"),login=$("loginDialog"),admin=$("adminDialog"),toast=$("toast");
const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
function say(s){toast.textContent=s;toast.classList.add("show");clearTimeout(say.t);say.t=setTimeout(()=>toast.classList.remove("show"),2200)}
async function load(){if(!sb){$("status").textContent="Configura Supabase siguiendo README.txt.";return}$("status").textContent="Cargando catálogo…";const {data,error}=await sb.from("catalog_items").select("*").order("created_at",{ascending:false});if(error){$("status").textContent="Error al cargar: "+error.message;return}items=data||[];render();$("status").textContent=items.length?`${items.length} elemento(s) publicados`:"El catálogo está listo para recibir publicaciones."}
function categories(){let old=filter.value,cats=[...new Set(items.map(x=>x.category).filter(Boolean))].sort();filter.innerHTML='<option value="">Todas las categorías</option>'+cats.map(c=>`<option value="${esc(c)}">${esc(c)}</option>`).join("");if(cats.includes(old))filter.value=old}
function renderCatalog(){let q=search.value.trim().toLowerCase(),c=filter.value,arr=items.filter(x=>(!c||x.category===c)&&(!q||`${x.id} ${x.name||""} ${x.category||""}`.toLowerCase().includes(q)));catalog.innerHTML=arr.map(x=>`<article class="card"><img src="${esc(x.image_url)}" alt="${esc(x.name||x.id)}" loading="lazy"><div class="cardBody">${x.name?`<div class="name">${esc(x.name)}</div>`:""}${x.category?`<div class="meta">${esc(x.category)}</div>`:""}<div class="id">${esc(x.id)}</div><div class="actions"><button class="primary copy" data-id="${esc(x.id)}">📋 Copiar ID</button></div></div></article>`).join("");empty.classList.toggle("hidden",arr.length!==0)}
function renderAdmin(){ $("adminList").innerHTML=items.length?items.map(x=>`<div class="adminItem"><img src="${esc(x.image_url)}" alt=""><div class="adminItemInfo"><strong>${esc(x.name||"Sin nombre")}</strong><span>ID: ${esc(x.id)}</span></div><button data-edit="${esc(x.id)}">Editar</button><button class="danger" data-del="${esc(x.id)}">Eliminar</button></div>`).join(""):'<p class="empty">Todavía no hay elementos.</p>'}
function render(){categories();renderCatalog();renderAdmin()}
$("adminBtn").onclick=async()=>{if(!sb){alert("Configura Supabase siguiendo README.txt.");return}const {data}=await sb.auth.getSession();user=data.session?.user||null;if(user){await load();admin.showModal()}else{ $("loginError").textContent="";login.showModal()}};
document.querySelectorAll("[data-close]").forEach(b=>b.onclick=()=>$(b.dataset.close).close());
$("loginForm").onsubmit=async e=>{e.preventDefault();const {data,error}=await sb.auth.signInWithPassword({email:$("email").value.trim(),password:$("password").value});if(error){$("loginError").textContent="No se pudo iniciar sesión. Comprueba correo y contraseña.";return}user=data.user;login.close();await load();admin.showModal()};
$("logout").onclick=async()=>{await sb.auth.signOut();user=null;admin.close();say("Sesión cerrada.")};
$("itemImage").onchange=()=>{file=$("itemImage").files[0]||null;if(file){$("preview").src=URL.createObjectURL(file);$("preview").style.display="block"}};
$("itemForm").onsubmit=async e=>{e.preventDefault();$("formError").textContent="";if(!user){$("formError").textContent="Inicia sesión primero.";return}let id=$("itemId").value.trim(),name=$("itemName").value.trim(),category=$("itemCategory").value.trim();const btn=$("saveItem");btn.disabled=true;btn.textContent="Guardando…";try{let image_url=editing?.image_url||"";if(file){let path=crypto.randomUUID()+"-"+file.name.replace(/[^a-zA-Z0-9._-]/g,"_");let {error}=await sb.storage.from("catalog-images").upload(path,file,{contentType:file.type});if(error)throw error;image_url=sb.storage.from("catalog-images").getPublicUrl(path).data.publicUrl}if(!image_url)throw Error("Selecciona una imagen.");let row={id,name:name||null,category:category||null,image_url,updated_at:new Date().toISOString()};let result=editing?await sb.from("catalog_items").update(row).eq("id",editing.id):await sb.from("catalog_items").insert(row);if(result.error)throw result.error;$("itemForm").reset();$("preview").style.display="none";file=null;editing=null;$("itemId").disabled=false;$("cancelEdit").style.display="none";await load();say("Publicado online.")}catch(err){$("formError").textContent=err.message||"Error al guardar"}finally{btn.disabled=false;btn.textContent=editing?"Guardar cambios":"Publicar elemento"}};
$("cancelEdit").onclick=()=>{editing=null;file=null;$("itemForm").reset();$("itemId").disabled=false;$("preview").style.display="none";$("cancelEdit").style.display="none";$("saveItem").textContent="Publicar elemento";$("formError").textContent=""};
$("adminList").onclick=async e=>{let ed=e.target.closest("[data-edit]"),del=e.target.closest("[data-del]");if(ed){editing=items.find(x=>x.id===ed.dataset.edit);if(!editing)return;$("itemId").value=editing.id;$("itemId").disabled=true;$("itemName").value=editing.name||"";$("itemCategory").value=editing.category||"";$("itemImage").value="";file=null;$("preview").src=editing.image_url;$("preview").style.display="block";$("saveItem").textContent="Guardar cambios";$("cancelEdit").style.display="inline-block"}if(del){if(!confirm("¿Eliminar este elemento?"))return;let {error}=await sb.from("catalog_items").delete().eq("id",del.dataset.del);if(error){say("Error: "+error.message);return}await load();say("Elemento eliminado.")}};
catalog.onclick=async e=>{let b=e.target.closest(".copy");if(!b)return;try{await navigator.clipboard.writeText(b.dataset.id);say("ID copiado.")}catch{say("No se pudo copiar automáticamente.")}};
search.oninput=renderCatalog;filter.onchange=renderCatalog;
if(sb)load();else $("status").textContent="Falta configurar Supabase. Consulta README.txt.";
